### ISSUE TITLE
[bug] panics on #6109347

### ISSUE THREAD

**Issue by lightsing** [scroll-tech/stateless-block-verifier#11]
```
thread 'tokio-runtime-worker' panicked at src/database.rs:77:9:
Should not be called. Code is either loaded or not needed (like EXTCODESIZE)
```

```
thread 'tokio-runtime-worker' panicked at /home/ubuntu/.cargo/git/checkouts/zkevm-circuits-462c2cba34f9b301/8cd233b/eth-types/src/lib.rs:900:26:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Need investigation

**Comment by lightsing** [comment]
cc @lispc
